### ISSUE TITLE
not a valid win32 application

### ISSUE THREAD

**Issue by litodagodog** [airyz/HTMLTestRunner-with-Screenshots#1]
hello can you help me how to fix this one?Im using your modified htmltestrunner with screenshots

>>> from sikuli.Sikuli import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sikuli\__init__.py", line 1, in <module>
    from sikuli import *
  File "C:\Python27\lib\site-packages\sikuli\sikuli.py", line 15, in <module>
    from jnius import autoclass
  File "C:\Python27\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by litodagodog** [comment]
i was able to fix the issue but when I run a testsuite screenshots are not added in htmlreport
:(
